### ISSUE TITLE
Need a little bit of help bringing deployment script up to latest version

### ISSUE THREAD

**Issue by ghost** [robhanlon22/etherpad-lite-heroku#4]
Hi, I know you're not maintaining this anymore, but if you could give me a little bit of info about the deployment script I can hopefully debug it.

Specifically, updating the etherpad-lite subtree leads to this error on heroku:

```
app[web.1]:     at Module.require (module.js:364:17)
app[web.1]:     at Object.<anonymous> (/app/etherpad-lite/src/node/utils/Settings.js:193:9)
app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
app[web.1]:     at Object.reloadSettings (/app/etherpad-lite/src/node/utils/Settings.js:140:40)
app[web.1]:               ^
app[web.1]: TypeError: Arguments to path.join must be strings
app[web.1]:     at Array.filter (native)
```

Internet search says this is related to updated node, and is going to require some tweaking.

The lines in the generated Settings.js are:

```
exports.reloadSettings = function reloadSettings() {
  // Discover where the settings file lives
  var settingsFilename = argv.settings || "settings.json";
  settingsFilename = path.resolve(path.join(root, settingsFilename));
```

and

```
/* Root path of the installation */
exports.root = path.normalize(path.join(npm.dir, ".."));
```

I think I can fix this, but I need to know how the wrapper is generating `Settings.js`. It's not clear to me from the `run.rb` file.

**Comment by ghost** [comment]
Never mind, I straightened it out by writing from scratch until it became clear. An initial working release available at https://github.com/talexand/etherpad-lite-heroku
